import { grafanaRulerGroupName } from 'app/features/alerting/unified/mocks/alertRuleApi';
import { PromAlertingRuleState, PromRuleType, PromRulesResponse } from 'app/types/unified-alerting-dto';

// TODO: Scaffold this out more to align with our needs for testing
export const getMockPrometheusRules: () => PromRulesResponse = () => ({
  status: 'success',
  data: {
    groups: [
      {
        file: 'test-folder-1',
        name: grafanaRulerGroupName,
        rules: [
          {
            state: PromAlertingRuleState.Firing,
            name: 'Grafana-rule',
            query: '',
            duration: 60,
            activeAt: '2024-06-11T10:29:50+01:00',
            alerts: [
              {
                labels: {
                  __grafana_autogenerated__: 'true',
                  __grafana_receiver__: 'asdasd',
                  alertname: 'Grafana-rule',
                },
                annotations: {},
                state: 'Alerting',
                activeAt: '2024-06-11T10:29:50+01:00',
                value: '1e+00',
              },
            ],
            totals: {
              alerting: 1,
            },
            totalsFiltered: {
              alerting: 1,
            },
            health: 'ok',
            type: PromRuleType.Alerting,
            lastEvaluation: '2024-06-11T10:59:50+01:00',
            evaluationTime: 4.006896,
          },
        ],
        totals: {
          firing: 1,
          inactive: 1,
        },
        interval: 60,
        lastEvaluation: '2024-06-11T10:59:50+01:00',
        evaluationTime: 7.006039,
      },
    ],
    totals: {
      error: 0,
      firing: 1,
      inactive: 0,
      pending: 0,
    },
  },
});
